DESC CLIENTE;

+------------+---------------+------+-----+---------+----------------+
| Field      | Type          | Null | Key | Default | Extra          |
+------------+---------------+------+-----+---------+----------------+
| IDCLIENTE  | int(11)       | NO   | PRI | NULL    | auto_increment |
| NOME       | varchar(50)   | NO   |     | NULL    |                |
| SEXO       | enum('M','F') | NO   |     | NULL    |                |
| EMAIL      | varchar(50)   | YES  | UNI | NULL    |                |
| CPF        | int(11)       | YES  | UNI | NULL    |                |
| ID_CLIENTE | int(11)       | YES  |     | NULL    |                |
+------------+---------------+------+-----+---------+----------------+

DESC ENDERECO;

+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| IDENDERECO | int(11)     | NO   | PRI | NULL    | auto_increment |
| RUA        | varchar(30) | NO   |     | NULL    |                |
| BAIRRO     | varchar(30) | NO   |     | NULL    |                |
| CIDADE     | varchar(30) | NO   |     | NULL    |                |
| ESTADO     | char(2)     | NO   |     | NULL    |                |
| ID_CLIENTE | int(11)     | YES  | UNI | NULL    |                |
+------------+-------------+------+-----+---------+----------------+

DESC TELEFONE;

+------------+-------------------------+------+-----+---------+----------------+
| Field      | Type                    | Null | Key | Default | Extra          |
+------------+-------------------------+------+-----+---------+----------------+
| IDTELEFONE | int(11)                 | NO   | PRI | NULL    | auto_increment |
| TIPO       | enum('RES','COM','CEL') | NO   |     | NULL    |                |
| NUMERO     | varchar(10)             | NO   |     | NULL    |                |
| ID_CLIENTE | int(11)                 | YES  | MUL | NULL    |                |
+------------+-------------------------+------+-----+---------+----------------+


/* RELATORIO GERAL DOS CLIENTES */
SELECT NOME, SEXO, EMAIL, CPF,
        RUA, BAIRRO, CIDADE, ESTADO,
        TIPO, NUMERO 
FROM CLIENTE T1 
INNER JOIN ENDERECO T2 ON T1.IDCLIENTE = T2.IDENDERECO
INNER JOIN TELEFONE T3 ON T2.IDENDERECO = T3.IDTELEFONE;


/* RELATORIO GERAL DOS CLIENTES HOMENS*/
SELECT NOME, SEXO, EMAIL, CPF,
        RUA, BAIRRO, CIDADE, ESTADO,
        TIPO, NUMERO 
FROM CLIENTE T1 
INNER JOIN ENDERECO T2 ON T1.IDCLIENTE = T2.IDENDERECO
INNER JOIN TELEFONE T3 ON T2.IDENDERECO = T3.IDTELEFONE
WHERE T1.SEXO = 'M';

SELECT * FROM CLIENTE
WHERE IDCLIENTE IN (10, 11, 12,16 , 17);

UPDATE CLIENTE SET SEXO = 'F'
WHERE IDCLIENTE IN (10, 11, 12,16 , 17);


/* RELATORIO GERAL DOS CLIENTES MULHERES*/
SELECT NOME, SEXO, EMAIL, CPF,
        RUA, BAIRRO, CIDADE, ESTADO,
        TIPO, NUMERO 
FROM CLIENTE T1 
INNER JOIN ENDERECO T2 ON T1.IDCLIENTE = T2.IDENDERECO
INNER JOIN TELEFONE T3 ON T2.IDENDERECO = T3.IDTELEFONE
WHERE T1.SEXO = 'F';

UPDATE CLIENTE SET SEXO = 'M'
WHERE IDCLIENTE IN (14);

/* QUANTIDADE DE HOMENS E MULHERES */
SELECT COUNT(*) AS TOTAL, SEXO
FROM CLIENTE
GROUP BY SEXO;


/* IDS E EMAIL DAS MULEHRES QUE MORAM NO CENTRO DO RJ QUE NAO TENHAM CELULAR */
SELECT IDCLIENTE, EMAIL, NOME, SEXO, TIPO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE CIDADE = 'RIO DE JANEIRO' AND BAIRRO LIKE 'CENTRO'
AND SEXO = 'F';






INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567', NULL);
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655', NULL);
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778', NULL);
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789', NULL);
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887', NULL);
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457', NULL);
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767', NULL);
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565', NULL);
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763', NULL);
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213', NULL);
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942', NULL);
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256', NULL);

/* CADASTRE UM ENDERECO PARA CADA CLIENTE */

INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);

/* CADASTRE TELEFONES PARA OS CLIENTES */


INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',20);
