CREATE DATABASE OFICINA;

USE OFICINA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	NUMERO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT 
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO,ID_COR)
);

/* CONSTRAINTS */

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);


ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);


ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);


/* ADICIONANDO REGRISTOS */

INSERT INTO MARCA (MARCA) VALUES 
('Toyota'), ('Volkswagen'), ('Ford'), ('Honda'), ('Chevrolet'), ('Fiat'), ('Hyundai'), ('Renault'), 
('Nissan'), ('BMW'), ('Mercedes'), ('Audi'), ('Kia'), ('Jeep'), ('Mitsubishi'), ('Peugeot'), 
('Citroen'), ('Volvo'), ('Chery'), ('Land Rover');

INSERT INTO COR (COR) VALUES 
('Branco'), ('Preto'), ('Prata'), ('Cinza'), ('Vermelho'), ('Azul'), ('Verde'), ('Amarelo'), 
('Bege'), ('Marrom'), ('Laranja'), ('Vinho'), ('Dourado'), ('Grafite'), ('Azul Marinho'), 
('Verde Musgo'), ('Rosa'), ('Roxo'), ('Cobre'), ('Pérola');

INSERT INTO CARRO (MODELO, PLACA, ID_MARCA) VALUES 
('Corolla', 'ABC1001', 1), ('Golf', 'ABC1002', 2), ('Mustang', 'ABC1003', 3), ('Civic', 'ABC1004', 4),
('Onix', 'ABC1005', 5), ('Uno', 'ABC1006', 6), ('HB20', 'ABC1007', 7), ('Sandero', 'ABC1008', 8),
('Kicks', 'ABC1009', 9), ('X3', 'ABC1010', 10), ('Classe C', 'ABC1011', 11), ('A3', 'ABC1012', 12),
('Sportage', 'ABC1013', 13), ('Renegade', 'ABC1014', 14), ('L200', 'ABC1015', 15), ('208', 'ABC1016', 16),
('C3', 'ABC1017', 17), ('XC60', 'ABC1018', 18), ('Tiggo 5x', 'ABC1019', 19), ('Evoque', 'ABC1020', 20);

INSERT INTO CARRO_COR (ID_CARRO, ID_COR) VALUES 
(1,1), (2,2), (3,5), (4,3), (5,1), (6,4), (7,6), (8,2), (9,3), (10,2),
(11,4), (12,1), (13,10), (14,11), (15,3), (16,5), (17,6), (18,1), (19,2), (20,14);

INSERT INTO CLIENTE (NOME, SEXO, ID_CARRO) VALUES 
('João Silva', 'M', 1), ('Maria Oliveira', 'F', 2), ('Carlos Souza', 'M', 3), ('Ana Costa', 'F', 4),
('Pedro Santos', 'M', 5), ('Julia Lima', 'F', 6), ('Roberto Rocha', 'M', 7), ('Fernanda Alves', 'F', 8),
('Lucas Pereira', 'M', 9), ('Beatriz Mendes', 'F', 10), ('Marcos Viana', 'M', 11), ('Camila Duarte', 'F', 12),
('André Felipe', 'M', 13), ('Letícia Gomes', 'F', 14), ('Ricardo Sales', 'M', 15), ('Patrícia Luz', 'F', 16),
('Fábio Júnior', 'M', 17), ('Simone Reis', 'F', 18), ('Gustavo Henrique', 'M', 19), ('Aline Moraes', 'F', 20);

INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE) VALUES 
('CEL', '998887711', 1), ('RES', '33445501', 1), ('COM', '32221101', 2), ('CEL', '987654301', 3),
('CEL', '912345601', 4), ('RES', '33221101', 5), ('COM', '35556601', 6), ('CEL', '991122301', 7),
('CEL', '988776601', 8), ('RES', '34445501', 9), ('COM', '31112201', 10), ('CEL', '977665501', 11),
('CEL', '966554401', 12), ('RES', '30001101', 13), ('CEL', '955443301', 14), ('COM', '36667701', 15),
('CEL', '944332201', 16), ('RES', '37778801', 17), ('CEL', '933221101', 18), ('CEL', '922110001', 19);


/* FAZENDO UM JOIN */

SELECT  C.NOME, C.SEXO,
        CA.MODELO, CA.PLACA,
        CC.COR, M.MARCA,
        T.TIPO, T.NUMERO
FROM CLIENTE C INNER JOIN CARRO CA
ON C.IDCLIENTE = CA.IDCARRO
INNER JOIN COR CC
ON CA.IDCARRO = CC.IDCOR
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN MARCA M
ON CA.IDCARRO = M.IDMARCA;

/* CRIANDO UMA VIEW */

CREATE VIEW v_RELATORIO_OFICINA AS 
SELECT  C.NOME, C.SEXO,
        CA.MODELO, CA.PLACA,
        CC.COR, M.MARCA,
        T.TIPO, T.NUMERO
FROM CLIENTE C INNER JOIN CARRO CA
ON C.IDCLIENTE = CA.IDCARRO
INNER JOIN COR CC
ON CA.IDCARRO = CC.IDCOR
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN MARCA M
ON CA.IDCARRO = M.IDMARCA;

SELECT NOME, MODELO, COR
FROM v_RELATORIO_OFICINA;

SELECT NOME, MODELO, COR
FROM v_RELATORIO_OFICINA
WHERE SEXO = "M";


SELECT NOME, MODELO, COR
FROM v_RELATORIO_OFICINA
WHERE SEXO = "F";