/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'JOAO@GMAIL.COM'
WHERE NOME LIKE 'JOA%';



UPDATE CLIENTE
SET ENDERECO = 'TIRADENTES - SERRA VERDE - IGUARITE - RJ'
WHERE NOME LIKE 'JOA%';