CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    HORAS INT(3) NOT NULL,
    VALOR FLOAT(10, 2)
);

INSERT INTO CURSOS VALUES(NULL, 'JAVA', 30, 500.00);
INSERT INTO CURSOS VALUES(NULL, 'FUNDAMENTOS DE BD', 40, 700.00);

SELECT * FROM CURSOS;

DELIMITER $

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), P_HORAS INT(3), p_VALOR FLOAT(10, 2))
BEGIN

    INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_VALOR);

END
$

DELIMITER ;

CALL CAD_CURSO('PYTHON', 35, 450.00);
CALL CAD_CURSO('POWER BI', 20, 250.00);
CALL CAD_CURSO('TABLEAU', 30, 650.00);
CALL CAD_CURSO('BI SQL SERVER', 80, 1200.00);
CALL CAD_CURSO('C++', 15, 150.00);
CALL CAD_CURSO('PROGAMACAO COMPETITIVA', 200, 3650.00);




DELIMITER $

CREATE PROCEDURE CONSULTAR_CURSO(P_IDCURSO INT(30))
BEGIN

    SELECT NOME, HORAS, VALOR FROM CURSOS
    WHERE IDCURSO = P_IDCURSO 
    ORDER BY VALOR;

END
$


DELIMITER ;

CALL CONSULTAR_CURSO(2);

DROP PROCEDURE CONSULTAR_CURSO;