SHOW DATABASES;

USE COMERCIO;

DESC CLIENTE;

INSERT INTO CLIENTE VALUES(NULL,'WESCLEY', 'M', 'WESCLEY@GLOBO.ORG', '2026598748',DEFAULT);;
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678',DEFAULT);
INSERT INTO CLIENTE VALUES(NULL,'JOAO', 'M', 'JOAO@ED.ORG', '32438748',DEFAULT);
INSERT INTO CLIENTE VALUES(NULL,'PAOLA', 'F', 'PAOLA@GMAIL.ORG', '1234438748',DEFAULT);
INSERT INTO CLIENTE VALUES(NULL,'LUIZ', 'M', 'LUIZ@ED.ORG', '789418230',DEFAULT);
INSERT INTO CLIENTE VALUES(NULL,'THAISSA', 'F', 'THAISSA@GMAIL.ORG', '1234567891',DEFAULT);


/* 1 X 1 */

DESC ENDERECO;


INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

SELECT * FROM ENDERECO;


/* 1 X N */

DESC TELEFONE;

INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);

SELECT * FROM TELEFONE;

SELECT * 
FROM CLIENTE T1 LEFT JOIN TELEFONE T2;