/* DELETANDO REGISTROS COM A CLAUDULA DELETE */

SELECT COUNT(*) FROM CLIENTE;

DELETE FROM CLIENTE
WHERE NOME = 'ANA';

INSERT INTO CLIENTE VALUES('ANA CLARA', 'F', 'A.CLARA@UOL.COM', 45638854, '45750058', 'COOPER LEAF - WILLIAMSBURG - KITCHENER');
