/* O COMANDO SELECT 
 selecao projecao e juncao
 */

 SELECT NOW() AS DATA_HORA;

 SELECT 'WESCLEY SOUZA';
 
 SELECT 'BANCO DE DADOS';

 /* ALIAS DE COLUNAS */ 

 SELECT NOME, SEXO, EMAIL FROM CLIENTES;

 SELECT NOME AS CLIENTE, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;