/* FRILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = "M";

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = "F";

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = "MG";

/* UTILIZANDO LIKE */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE "MG";

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE "%MG";