SELECT  C.NOME,
        C.SEXO,
        C.EMAIL,
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E 
ON  C.IDCLIENTE = E.ID_CLIENTE;


CREATE VIEW RELATORIO AS 
SELECT  C.NOME,
        C.SEXO,
        C.EMAIL,
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E 
ON  C.IDCLIENTE = E.ID_CLIENTE;

SELECT * FROM RELATORIO;

SHOW TABLES;

/*APAGAR UMA VIEW */

DROP VIEW RELATORIO;


/*INSERINDO UMA VIEW */
CREATE VIEW V_RELATORIO AS 
SELECT  C.NOME,
        C.SEXO,
        IFNULL(C.EMAIL, '***********') AS 'EMAIL'3,
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E 
ON  C.IDCLIENTE = E.ID_CLIENTE;


SELECT NOME, NUMERO, ESTADO 
FROM V_RELATORIO;