/* OPERACOES LOGICAS
OR - PARA QUE A SAIDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDICAO SEJA VERDADEIRA

AND- PARA QUE A SAIDA DA QUERY SEJA VERDADEIRA, BASTA QUE TODAS AS CONDICOES SEJAM VERDADEIRAS
*/

/* OR - OU */

SHOW DATABASES;

USE PROJETO;

SELECT * FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

/* AND - E */ 
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

