/* AUTORELACIONAMENTO */

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    HORAS INT, 
    VALOR FLOAT(10,2),
    ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERECES CURSOS(IDCURSO);

INSERT INTO CURSOS (NULL, 'BD RELACIONAL',20, 400.00, NULL);
INSERT INTO CURSOS (NULL, 'BUSINESS ITELLIGENCE',40, 600.00, 1);
INSERT INTO CURSOS (NULL, 'RELATORIOS AVANÇADOS', 25, 350.00, 2);
INSERT INTO CURSOS (NULL, 'LOGICA DE PROGRAMACAO',15, 150.00, NULL);
INSERT INTO CURSOS (NULL, 'RUBY',30, 500.00, 4);


EXERCICIO

/* NOME, VALOR, HORAS  E O NOME DO PRE REQUISITO DO CURSO */

SELECT C.NOME AS CURSO,C.VALOR AS VALOR, C.HORAS AS CARGA, IFNULL(P.NOME, "----") AS PREREQ
FROM  CURSOS C 
LEFT JOIN CURSOS P
ON P.IDCURSO = C.ID_PREREQ;